spring.application.name=CarRrental
#spring.datasource.url=jdbc:postgresql://carrentaldentifier.cx2kas2q6div.us-east-2.rds.amazonaws.com/carrentaldb

#spring.datasource.username=CaradminDb
#spring.datasource.password=yash1234
spring.datasource.url=jdbc:postgresql://localhost:5432/carrentaldb
spring.datasource.username=postgres
spring.datasource.password=yash

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (Optional) keep logs readable
logging.level.org.hibernate.SQL=DEBUG

app.jwt.secret=fsfiherfesdjg;ohsdghshgelhoigai#@#@$@#$%#$%Ê43437drlgherity438435$#%#$^%#$Ut9eutp9e5yjilfdgh77474557fSDF#$%$$$$
app.jwt.expiryMinutes=60


# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=developer3171@gmail.com
spring.mail.password=fzyb itqq pksa cbth

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# (optional) helpful for debugging
logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG
