spring.application.name=CarRrental

# PostgreSQL - hardcoded values
spring.datasource.url=jdbc:postgresql://localhost:5432/carrentaldb
spring.datasource.username=postgres
spring.datasource.password=yash

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG

# JWT
app.jwt.secret=fsfiherfesdjg;ohsdghshgelhoigai#@#@$@#$%#$%�43437drlgherity438435$#%#$^%#$Ut9eutp9e5yjilfdgh77474557fSDF#$%$$$$
app.jwt.expiryMinutes=60

# Gmail SMTP - hardcoded
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=developer3171@gmail.com
spring.mail.password=fzybitqqpksacbth

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG

# Frontend URL for emails
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}